//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRP_proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLETA
    {
        public int num_boleta { get; set; }
        public System.DateTime fec_boleta { get; set; }
        public int idCliente { get; set; }
        public int idParqueo { get; set; }
    
        public virtual tb_cliente tb_cliente { get; set; }
        public virtual tb_parqueo tb_parqueo { get; set; }
    }
}
